name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
        id: go

      - name: Get dependencies
        run: |
          mkdir -p $GOPATH/bin
          export PATH=$PATH:$GOPATH/bin

      - name: Build
        run: go build -o prmanager_exe -v .

      - name: Vet
        run: go vet ./...

      - name: Formatting
        run: test -z $(go fmt ./...)

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          install-go: false